# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Syn Syn-Ack Ack
tagline:          'Bite-sized information security'
description:      'Information Security news and how-tos in 200 words or less'
url:              fwalloe.github.io/SSAA/

author:
  name:           'NULL'
  url:            https://twitter.com/_SYN_ACK_

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
