# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Syn Syn-Ack Ack
tagline:             'Bite-sized information security'
description:         'Information Security news and how-tos in 200 words or less.'
url:                 http://fwalloe/SSAA
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              NULL
  url:               https://twitter.com/_SYN_ACK_
  email:             NULL

# Custom vars
version:             1.0.0
